### ISSUE TITLE
Doesn't work inside repos that are for Github Enteprise

### ISSUE THREAD

**Issue by bondezbond** [johnmanjiro13/gh-bump#1]
`gh bump` does not work on a repo tied to GHE when you are inside that directory. Is there a way to have gh bump figure out which GH_HOST to use like other gh commands in the cli?

Current workaround is to set the `GH_HOST=ghe.company.com gh bump`

**Comment by johnmanjiro13** [comment]
Hi @bondezbond

`gh bump` exec gh binary of your shell, so I think that this extension should follow usage of environment variables of the gh command.
But if this problem doesn't follow the behavior of the gh command, I may fix it.

I can't check this problem because I don't have any repos tied to GHE. So can you give me more information?
What error messages are displayed?
How do you do run other gh commands inside repos tied to GHE?

**Comment by bondezbond** [comment]
So when you run `gh bump` on a GHE repo. There's no error. It just doesn't pull the current tags from the repo as expected. It just outputs `New Version` like so
![image](https://user-images.githubusercontent.com/4400773/144859328-5c23a9be-37bc-4b6a-864a-2a23aea3e096.png)

If I add `GH_HOST=my.company.com gh bump` it queries the remote version correctly and outputs like so

![image](https://user-images.githubusercontent.com/4400773/144859480-2401f684-0945-457b-9744-800756d6055a.png)


Other commands I run like `gh run list` works without the need of setting `GH_HOST`

![image](https://user-images.githubusercontent.com/4400773/144859604-86d02eaf-fdb2-441f-aa49-729e47c93131.png)

**Comment by johnmanjiro13** [comment]
Thank you for your cooperation.

`gh bump` outputs `New Version` when `gh release view` command returns HTTP 404 as below.
https://github.com/johnmanjiro13/gh-bump/blob/main/main.go#L108

Can you give me your outputs when you run `gh release view -R <your_repository>` in your repository? (Of course, you can hide the detail.)
If the command outputs `HTTP 404: Not Found`, this problem is caused by gh cli.
(gh cli uses github.com for hostname by default. https://github.com/cli/cli/issues/3232#issuecomment-799592227)

**Comment by johnmanjiro13** [comment]
Thank you for your cooperation.

`gh bump` outputs `New Version` when `gh release view -R <repository>` command returns HTTP 404 as below.
https://github.com/johnmanjiro13/gh-bump/blob/main/main.go#L110
The -R option of `gh release view` used so that you can specify of remote repository by gh bump.

gh cli uses github.com for hostname by default where the current repository is not the context. https://github.com/cli/cli/issues/3232#issuecomment-799592227

Therefore, this problem is caused by gh cli.
If gh cli fix this default, you can use gh bump without GH_HOST.

**Comment by johnmanjiro13** [comment]
I published v0.2.0 now.
Please upgrade and check it.

```
gh extension upgrade johnmanjiro13/gh-bump
```

**Comment by bondezbond** [comment]
Hi @johnmanjiro13. Just ugprade the extension but it still doesn't pull without `GH_HOST` is there a debug line I can run to see what is happening?

**Comment by johnmanjiro13** [comment]
Oh... I'm sorry.

> Is there a debug line I can run to see what is happening?

I think you fork this repository and debug main.go.

**Comment by bondezbond** [comment]
not sure if this helps. But I noticed when I run `gh release view -R OrgName/Repo` it checks for api.github.com.

But if I just run `gh release view` it actually polls the correct ghe repo

**Comment by johnmanjiro13** [comment]
@bondezbond 

I had forgot to upgrade tag in the gh-bump script.
I fixed it, so please retry upgrade 🙇

**Comment by bondezbond** [comment]
I can confirm it works now! 🥳

**Comment by johnmanjiro13** [comment]
Yeah! Thank you for your contribution!
